# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestUserNomatch():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_userNomatch(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1936, 1056)
    text = self.driver.find_element(By.XPATH, "//div[@class=\'usermenu\']").text
    assert text != "Bạn đang truy cập với tư cách khách vãng lai\\\\nĐăng nhập"
    self.driver.find_element(By.CSS_SELECTOR, ".btn-open > .icon").click()
    self.driver.find_element(By.NAME, "q").send_keys("aaa")
    self.driver.find_element(By.XPATH, "//div[@id=\'searchform-navbar\']/form/div/div/button/i").click()
    assert self.driver.find_element(By.XPATH, "//div[@class=\'alert alert-info alert-block fade in  alert-dismissible\']").text == "No results\\\\n×\\\\nDismiss this notification"
  
