# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStudentleavesallbutonequestionblank():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_studentleavesallbutonequestionblank(self):
    self.driver.get("https://school.moodledemo.net/my/courses.php")
    self.driver.set_window_size(1936, 1056)
    self.driver.find_element(By.LINK_TEXT, "Cross-cultural Communication").click()
    self.driver.find_element(By.LINK_TEXT, "Cultural Dimensions formative quiz.").click()
    self.driver.find_element(By.XPATH, "//form/button").click()
    self.driver.find_element(By.XPATH, "//div[contains(@id, \'1_\')]/div[contains(text(),\'Power Distance\')]").click()
    self.driver.find_element(By.ID, "mod_quiz-next-nav").click()
    self.driver.find_element(By.XPATH, "//button[contains(.,\'Submit all and finish\')]").click()
    assert self.driver.find_element(By.XPATH, "//div[@class=\'quiz-submission-confirmation-content\']").text == "Once you submit your answers, you won’t be able to change them.\\\\nQuestions without a response: 9"
    self.driver.find_element(By.CSS_SELECTOR, ".modal-footer > .btn-primary").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) > .cell:nth-child(2)").click()
    assert self.driver.find_element(By.XPATH, "//tr[5]/td").text == "1.00 out of 10.00 (10%)"
  
